# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Evan's Blog
tagline:             'A place for words'
description:         'Made Possible by the <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme '
url:                 http://localhost:4000
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Evan Dumas
  url:               https://twitter.com/eedumas
  email:             eedumas@gmail.com

# Custom vars
version:             0.0.3