# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Evan's Blog
tagline:             'A place for words'
description:         'Made Possible by <a href="http://jekyllrb.com" target="_blank">Jekyll</a>'
url:                 
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Evan Dumas
  url:               https://twitter.com/eedumas
  email:             eedumas@gmail.com

# Custom vars
version:             0.0.3

baseurl: "/46fdcc6902eb6841f2fc62595172cc29cac9740a"
production_url : http://eedumas-maker.github.io.com/46fdcc6902eb6841f2fc62595172cc29cac9740a
BASE_PATH : http://eedumas-maker.com/46fdcc6902eb6841f2fc62595172cc29cac9740a